version: "3.3"

networks:
  net:
    driver: overlay
    attachable: true

configs:
  prom_config:
    file: ./prometheus/weave-cortex.yml
  prom_entrypoint:
    file: ./prometheus/docker-entrypoint.sh
  prom_rules:
    file: ./prometheus/alert.rules
  alertmanager_config:
    file: ./alertmanager/alertmanager.yml
  caddy_config:
    file: ./caddy/Caddyfile

services:
  gateway:
    image: functions/gateway:0.6.13
    environment:
      faas_nats_address: "nats"
      faas_nats_port: 4222
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
    networks:
      - net
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - 'node.role == manager'

  nats:
    image: nats-streaming:0.6.0
    ports:
      - 4222:4222
      - 8222:8222
    command: "--store memory --cluster_id faas-cluster"
    networks:
      - net
    deploy:
      placement:
        constraints:
          - 'node.role == manager'

  queue-worker:
    image: functions/queue-worker:0.4
    networks:
        - net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 20
        window: 380s
      placement:
        constraints:
          - 'node.role == manager'

  prometheus:
    image: prom/prometheus:v1.8.2
    configs:
      - source: prom_entrypoint
        target: /etc/prometheus/docker-entrypoint.sh
        mode: 0550
      - source: prom_config
        target: /etc/prometheus/weave-cortex.yml
      - source: prom_rules
        target: /etc/prometheus/alert.rules
    entrypoint:
      - '/etc/prometheus/docker-entrypoint.sh'
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-web.console.libraries=/etc/prometheus/console_libraries'
      - '-web.console.templates=/etc/prometheus/consoles'
      - '-storage.local.target-heap-size=1073741824'
      - '-storage.local.retention=12h'
      - '-alertmanager.url=http://alertmanager:9093'
    environment:
      - WEAVE_TOKEN=$WEAVE_TOKEN
      - no_proxy=gateway
    networks:
      - net
    deploy:
      placement:
        constraints:
          - 'node.role != manager'

  alertmanager:
    image: prom/alertmanager:v0.9.1
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/alertmanager.yml
    command:
      - '-config.file=/etc/alertmanager/alertmanager.yml'
      - '-storage.path=/alertmanager'
    environment:
      no_proxy: "gateway"
    networks:
      - net
    deploy:
      placement:
        constraints:
          - 'node.role != manager'

  echoit:
    image: functions/alpine:health
    labels:
      function: "true"
    networks:
      - net
    environment:
      fprocess: "cat"
      no_proxy: "gateway"
      com.faas.max_replicas: "20"
      https_proxy: $https_proxy
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints:
          - 'node.role != manager'

  caddy:
    image: stefanprodan/caddy
    ports:
      - "80:80"
      - "9090:9090"
      - "9093:9093"
    networks:
      - net
    environment:
      - ADMIN_USER=${USER:-admin}
      - ADMIN_PASSWORD=${PASSWORD:-admin}
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role != manager
