version: "3.3"

networks:
  net:
    driver: overlay

services:

  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - '--docker'
      - '--docker.swarmmode'
      - '--docker.domain=weavedx.com'
      - '--docker.watch'
      - '--web'
      - '--logLevel=DEBUG'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-1

  portainer:
    image: portainer/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    deploy:
      labels:
        - "traefik.port=9000"
        - "traefik.enable=true"
        - "traefik.docker.network=lb_net"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend=portainer"
        - "traefik.frontend.entryPoints=http"
        - "traefik.frontend.rule=Host:portainer.weavedx.com"
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
