version: "3.3"

networks:
  mongo:
    external: true
  mongos:
    external: true

volumes:
    data: {}
    cfg: {}

services:

  data1:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-1

  data2:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-2

  data3:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - data:/data/db
    command: mongod --shardsvr --replSet datars --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-3

  cfg1:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-1

  cfg2:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-2

  cfg3:
    image: mongo:3.4
    networks:
      - mongo
    volumes:
      - cfg:/data/configdb
    command: mongod --configsvr --replSet cfgrs --smallfiles --port 27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-worker-3

  mongos1:
    image: mongo:3.4
    networks:
      - mongo
      - mongos
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-2

  mongos2:
    image: mongo:3.4
    networks:
      - mongo
      - mongos
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-3

  bootstrap:
    image: stefanprodan/mongo-bootstrap:latest
    networks:
      - mongo
    ports:
      - 9090:9090
    command:
      - '-dataSet=datars/data1:27017,data2:27017,data3:27017'
      - '-configSet=cfgrs/cfg1:27017,cfg2:27017,cfg3:27017'
      - '-mongos=mongos1:27017,mongos2:27017'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-1
