version: "3.3"

networks:
  mongos:
    external: true
  monitoring:
    external: true

services:

  mongos-exporter:
    image: forekshub/percona-mongodb-exporter:latest
    networks:
      - mongos
      - monitoring
    environment:
      - MONGODB_URL=mongodb://mongos1:27017,mongos2:27017/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-1

  mongo-exporter:
    image: forekshub/percona-mongodb-exporter:latest
    networks:
      - mongo
      - monitoring
    environment:
      - MONGODB_URL=mongodb://mongos1:27017,mongos2:27017/
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager-2
