version: "3.3"

services:

  portainer:
    image: portainer/portainer:latest
    ports:
      - 80:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
